pipeline {
    agent any

    stages {
        stage('Build Frontend') {
            steps {
                // Cambia al directorio del frontend
                dir('PrestaBanco-frontend') {
                    // Instala las dependencias y construye el proyecto
                    bat 'npm install' // Usa 'sh' si estás en un entorno Unix/Linux
                    bat 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                // Construye la imagen Docker
                script {
                    bat 'docker build -t tinyantu/prestabanco-frontend:latest -f PrestaBanco-frontend/Dockerfile PrestaBanco-frontend'
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dckhubpassword', variable: 'dhpsw')]) {
                        bat 'docker login -u tinyantu -p %dhpsw%'
                    }
                    bat 'docker push tinyantu/prestabanco-frontend:latest'
                }
            }
        }
    }
}
